### ISSUE TITLE
Spinner Code

### ISSUE THREAD

**Issue by beginmani** [beginmani/manager#2]
After adding the code for spinner, the app is not working.

![image](https://user-images.githubusercontent.com/24914126/51721046-17db7980-2076-11e9-85e1-cec2ceefbe77.png)

**Comment by lavisht22** [comment]
Search the internet before posting silly issues.

This was an issue with an external dependency and not the code. Latest version of Firebase is unstable and hence was causing this issue. I have reverted Firebase to an older version so that the application works. Also add more description while writing issues.
